% read text file generated by tedEvaluation2D
% then write report of per slice normalized error

inputTEDroot = '/home/thanuja/RESULTS/cvpr/TED2/tedOut/rfc_stc';
% inputTEDFile = '/home/thanuja/RESULTS/cvpr/TED2/rfc_stc_cnn_stc/ted_output_30.txt';
% errorReportFileName = ''; % there are 5 error reports: fp,fn,fm,fs,tot
errorReportRoot = inputTEDroot;
groundtruthDir = '/home/thanuja/DATA/ISBI2012/train-labels';
startImInd = 21;
endImInd = 30;
imType = 'tif';

% format = '%s %f, %s %f, VOI total: 5.11965; RAND: 0.0489372, ARAND: 0.906683; 
% DO_FP: 10, DO_FN: 29, DO_PRE: 0.87013, DO_REC: 0.697917, DO_FS: 0.774566, 
% DO_MEAN_M1: 62.1795, DO_STD_M1: 24.4636, DO_MEAN_M2: 69.2686, 
% DO_STD_M2: 23.8326, DO_MEAN_DICE: 0.731236, DO_STD_DICE: 0.239251; 
% TED FP: 4, TED FN: 7, TED FS: 14, TED FM: 30, TED Total: 55'
numImages = 10;
format = '%s';

slicesPerImage = getNumSlicesPerImage(groundtruthDir,startImInd,endImInd,imType);
totSlices = sum(slicesPerImage);

inputFileList = dir(fullfile(inputTEDroot,strcat('*.txt')));

for j=1:numel(inputFileList)
    inputTEDFile = fullfile(inputTEDroot,inputFileList(j).name);
    fid = fopen(inputTEDFile,'r');

    tline = fgets(fid);
    tline = strrep(tline,';',',');

    ted.voiSplit = zeros(numImages,1);  
    ted.voiMerge = zeros(numImages,1);
    ted.voiTot = zeros(numImages,1); 
    ted.randind = zeros(numImages,1);
    ted.arand = zeros(numImages,1);
    ted.tedFP = zeros(numImages,1);
    ted.tedFN = zeros(numImages,1);
    ted.tedFS = zeros(numImages,1);
    ted.tedFM = zeros(numImages,1);
    ted.tedTot = zeros(numImages,1);
    i = 0;

    

    while ischar(tline)
        if(length(tline)>10)
            % we have a ted output string
            disp(tline)
            tline = strrep(tline,' ','');
            i = i+1;
            % get errors per image
            [ted.voiSplit(i),ted.voiMerge(i),ted.voiTot(i), ted.randind(i),...
                ted.arand(i),ted.tedFP(i), ted.tedFN(i), ted.tedFS(i),...
                ted.tedFM(i), ted.tedTot(i)] ...
                = parseTEDline(tline);
        end

        tline = fgets(fid);
        tline = strrep(tline,';',',');
    end
    fclose(fid);
    
    % writeTEDerrorsToFile(ted,totSlices,errorReportFileName);
    writeTEDerrorsReports(ted,totSlices,errorReportRoot)

end